groups:
  - name: docker_container_alerts
    rules:
      - alert: ContainerDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Container {{ $labels.job }} is down"
          description: "Container {{ $labels.job }} has been down for more than 1 minute"

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.container_name }}"
          description: "CPU usage is above 80% for 5 minutes"

      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage on {{ $labels.container_name }}"
          description: "Memory usage is above 90% for 5 minutes"

  - name: csp_service_alerts
    rules:
      - alert: ChromaServiceDown
        expr: up{job="csp-chroma"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Chroma vector database is down"
          description: "Chroma service has been unreachable for 2 minutes"

      - alert: QdrantServiceDown
        expr: up{job="csp-qdrant"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Qdrant vector database is down"
          description: "Qdrant service has been unreachable for 2 minutes"

      - alert: WeaviateServiceDown
        expr: up{job="csp-weaviate"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Weaviate vector database is down"
          description: "Weaviate service has been unreachable for 2 minutes"

      - alert: RedisServiceDown
        expr: up{job="csp-redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis cache is down"
          description: "Redis service has been unreachable for 1 minute"

      - alert: PostgresServiceDown
        expr: up{job=~"csp-postgres.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL service {{ $labels.job }} has been unreachable for 1 minute"
