app_name: "Enhanced CSP System"
version: "2.0.0"
debug: false
environment: "development"
host: "0.0.0.0"
port: 8000
workers: 1
reload: false

# Use PostgreSQL since it's running (much better than SQLite for production)
database:
  url: "postgresql+asyncpg://postgres:password@localhost:5432/enhanced_csp"
  echo: false
  pool_size: 10
  max_overflow: 20

# Use the Redis container that's already running
redis:
  url: "redis://localhost:6379/0"
  max_connections: 10
  retry_on_timeout: true

runtime:
  execution_model: "MULTI_THREADED"
  max_workers: 4
  memory_limit_gb: 8.0
  enable_monitoring: true
  enable_optimization: true
  enable_debugging: false

ai:
  enable_llm_integration: false

monitoring:
  enable_prometheus: true
  metrics_port: 9090

secret_key: "dev-secret-key-change-in-production"
api_key_header: "X-CSP-API-Key"
enable_auth: false
