version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: csp_jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Collector HTTP
      - "14250:14250"  # Collector gRPC
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    volumes:
      - jaeger_data:/badger
    networks:
      - scripts_csp-network
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: csp_otel_collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./tracing/config/otel-collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4319:4317"    # OTLP gRPC
      - "4320:4318"    # OTLP HTTP
      - "8888:8888"    # Prometheus metrics
    networks:
      - scripts_csp-network
    depends_on:
      - jaeger

networks:
  scripts_csp-network:
    external: true

volumes:
  jaeger_data:
    driver: local
