apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enhanced-csp.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "enhanced-csp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "enhanced-csp.name" . }}
    spec:
      containers:
        - name: node
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 4001
          env:
            - name: P2P_STUN_SERVERS
              value: "{{ join "," .Values.p2p.stunServers }}"
