service:
  http_port: 6333
  grpc_port: 6334
  max_request_size_mb: 1024
  max_workers: 0
  enable_cors: true

storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  on_disk_payload: true
  performance:
    max_search_threads: 0
    max_optimization_threads: 1

cluster:
  enabled: false

log_level: INFO
