version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: csp_loki
    command: -config.file=/etc/loki/loki.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - ./loki/recording_rules.yml:/loki/rules/recording_rules.yml
      - loki_data:/loki
    networks:
      - monitoring_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  promtail:
    image: grafana/promtail:latest
    container_name: csp_promtail
    command: -config.file=/etc/promtail/promtail.yml
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../logs:/var/log/csp:ro
    networks:
      - monitoring_network
    restart: unless-stopped
    depends_on:
      - loki

networks:
  monitoring_network:
    external: true
    name: scripts_csp-network

volumes:
  loki_data:
    driver: local
