# monitoring/docker-compose.exporters.yml
version: '3.8'

services:
  # PostgreSQL Exporter for main database
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: csp_postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://csp_user:${DB_PASSWORD:-csp_secure_pass_2024!}@csp_postgres:5432/csp_system?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - scripts_csp-network
    restart: unless-stopped

  # PostgreSQL Exporter for AI models database
  postgres_ai_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: csp_postgres_ai_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://csp_user:${DB_PASSWORD:-csp_secure_pass_2024!}@csp_ai_models_db:5432/ai_models?sslmode=disable"
    ports:
      - "9188:9187"
    networks:
      - scripts_csp-network
    restart: unless-stopped

  # PostgreSQL Exporter for vector database
  postgres_vector_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: csp_postgres_vector_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://csp_user:${DB_PASSWORD:-csp_secure_pass_2024!}@csp_postgres_vector:5432/csp_vectors?sslmode=disable"
    ports:
      - "9189:9187"
    networks:
      - scripts_csp-network
    restart: unless-stopped

  # Redis Exporter
  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: csp_redis_exporter
    environment:
      REDIS_ADDR: "redis://csp_redis:6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD:-redis_secure_pass_2024!}"
    ports:
      - "9121:9121"
    networks:
      - scripts_csp-network
    restart: unless-stopped

  # MongoDB Exporter
  mongodb_exporter:
    image: percona/mongodb_exporter:0.40
    container_name: csp_mongodb_exporter
    command:
      - "--mongodb.uri=mongodb://csp_admin:${MONGO_PASSWORD:-mongo_secure_pass_2024!}@csp_mongodb:27017"
      - "--collect-all"
    ports:
      - "9216:9216"
    networks:
      - scripts_csp-network
    restart: unless-stopped

  # Node Exporter for system metrics
  node_exporter:
    image: prom/node-exporter:latest
    container_name: csp_node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - scripts_csp-network
    restart: unless-stopped

  # Blackbox Exporter for endpoint probing
  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: csp_blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox_exporter/config.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - scripts_csp-network
    restart: unless-stopped

  # Process Exporter
  process_exporter:
    image: ncabatoff/process-exporter:latest
    container_name: csp_process_exporter
    ports:
      - "9256:9256"
    volumes:
      - /proc:/host/proc:ro
      - ./process_exporter/config.yml:/config/process_exporter.yml
    command:
      - '--procfs=/host/proc'
      - '--config.path=/config/process_exporter.yml'
    networks:
      - scripts_csp-network
    restart: unless-stopped

networks:
  scripts_csp-network:
    external: true