version: '3.8'

services:
  breach-benchmark:
    build: .
    environment:
      - TARGET_HOST=host.docker.internal
      - TARGET_PORT=8000
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./reports:/app/reports
      - ./logs:/app/logs
    networks:
      - csp-network
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - csp-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: benchmark_db
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - csp-network

networks:
  csp-network:
    external: true

volumes:
  postgres_data:
