global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'csp-monitor'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Core Services
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'csp-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'csp-network-nodes'
    static_configs:
      - targets: 
        - 'network_node_1:8080'
        - 'network_node_2:8080'
        - 'network_node_3:8080'
    metrics_path: '/metrics'

  # Database Exporters
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  # Vector Databases
  - job_name: 'chroma'
    static_configs:
      - targets: ['csp_chroma:8200']
    metrics_path: '/api/v1/heartbeat'

  - job_name: 'qdrant'
    static_configs:
      - targets: ['csp_qdrant:6333']
    metrics_path: '/metrics'

  - job_name: 'weaviate'
    static_configs:
      - targets: ['csp_weaviate:8080']
    metrics_path: '/v1/meta'

  # System Monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'

  # Application Components
  - job_name: 'csp-auth-service'
    static_configs:
      - targets: ['api:8001']
    metrics_path: '/metrics'

  - job_name: 'csp-ai-service'
    static_configs:
      - targets: ['api:8002']
    metrics_path: '/metrics'

  - job_name: 'csp-engine'
    static_configs:
      - targets: ['api:8003']
    metrics_path: '/metrics'

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
