global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'csp-monitor'
    environment: 'docker'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CSP Services (from your running containers)
  - job_name: 'csp-chroma'
    static_configs:
      - targets: ['csp_chroma:8200']
    metrics_path: '/api/v1/heartbeat'
    scrape_interval: 30s

  - job_name: 'csp-qdrant'
    static_configs:
      - targets: ['csp_qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'csp-weaviate'
    static_configs:
      - targets: ['csp_weaviate:8080']
    metrics_path: '/v1/meta'
    scrape_interval: 30s

  - job_name: 'csp-redis'
    static_configs:
      - targets: ['csp_redis:6379']
    scrape_interval: 30s

  - job_name: 'csp-postgres'
    static_configs:
      - targets: ['csp_postgres:5432']
    scrape_interval: 30s

  - job_name: 'csp-postgres-vector'
    static_configs:
      - targets: ['csp_postgres_vector:5434']
    scrape_interval: 30s

  - job_name: 'csp-ai-models-db'
    static_configs:
      - targets: ['csp_ai_models_db:5433']
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
