global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'csp-monitor'
    environment: '${CSP_ENVIRONMENT:-development}'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CSP API
  - job_name: 'csp-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL databases
  - job_name: 'postgres-main'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  - job_name: 'postgres-ai-models'
    static_configs:
      - targets: ['postgres_ai_models:5432']

  - job_name: 'postgres-vector'
    static_configs:
      - targets: ['postgres_vector:5432']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  # Vector Databases
  - job_name: 'chroma'
    static_configs:
      - targets: ['chroma:8200']
    metrics_path: '/api/v1/heartbeat'

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'

  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:8080']
    metrics_path: '/v1/meta'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
