# File: monitoring/prometheus/prometheus-complete.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'csp-monitor'
    environment: '${CSP_ENVIRONMENT:-production}'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ============================================================================
  # CORE SERVICES
  # ============================================================================
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CSP Backend API
  - job_name: 'csp-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # CSP Network Nodes
  - job_name: 'csp-network-nodes'
    static_configs:
      - targets: 
        - 'network_node_1:6969'
        - 'network_node_2:6969'
        - 'network_node_3:6969'
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):.*'
        replacement: '${1}'

  # ============================================================================
  # DATABASE EXPORTERS
  # ============================================================================
  
  # PostgreSQL Main Database
  - job_name: 'postgres-main'
    static_configs:
      - targets: ['postgres_exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres_exporter:9187

  # PostgreSQL AI Models Database
  - job_name: 'postgres-ai-models'
    static_configs:
      - targets: ['postgres_ai_exporter:9187']

  # PostgreSQL Vector Database
  - job_name: 'postgres-vector'
    static_configs:
      - targets: ['postgres_vector_exporter:9187']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']

  # ============================================================================
  # VECTOR DATABASES
  # ============================================================================
  
  - job_name: 'chroma'
    static_configs:
      - targets: ['csp_chroma:8200']
    metrics_path: '/api/v1/heartbeat'
    scrape_interval: 30s
    scrape_timeout: 10s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: __name__
        replacement: 'chroma_up'

  - job_name: 'qdrant'
    static_configs:
      - targets: ['csp_qdrant:6333']
    metrics_path: '/metrics'

  - job_name: 'weaviate'
    static_configs:
      - targets: ['csp_weaviate:8080']
    metrics_path: '/v1/meta'
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: __name__
        replacement: 'weaviate_up'

  # ============================================================================
  # SYSTEM MONITORING
  # ============================================================================
  
  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Process Exporter
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process_exporter:9256']

  # ============================================================================
  # BLACKBOX MONITORING
  # ============================================================================
  
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api:8000/health
        - http://api:8000/api/v1/status
        - http://network_node_1:8080/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # ============================================================================
  # SERVICE DISCOVERY
  # ============================================================================
  
  # Docker service discovery for dynamic container monitoring
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      # Only monitor containers with prometheus labels
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: 'true'
        action: keep
      # Use container name as instance
      - source_labels: [__meta_docker_container_name]
        target_label: instance
      # Extract port from label
      - source_labels: [__meta_docker_container_label_prometheus_port]
        target_label: __address__
        replacement: '${1}'
      # Extract metrics path from label
      - source_labels: [__meta_docker_container_label_prometheus_path]
        target_label: __metrics_path__
        replacement: '${1}'
