global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@csp-system.local'

route:
  group_by: ['alertname', 'container_name']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    repeat_interval: 5m

receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://localhost:5001/webhook'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://localhost:5001/webhook/critical'
    send_resolved: true
  # Add email or Slack configuration here
  # email_configs:
  # - to: 'admin@yourdomain.com'
  #   subject: 'CRITICAL: CSP System Alert'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'container_name']
