name: Build and Test

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: >-
            pip-${{ runner.os }}-${{ hashFiles('enhanced_csp/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r enhanced_csp/requirements.txt
          pip install ruff mypy black pytest pytest-cov
      - name: Run Ruff
        run: ruff enhanced_csp
      - name: Run MyPy
        run: mypy enhanced_csp
      - name: Check formatting
        run: black --check enhanced_csp
      - name: Run tests
        run: pytest --cov=enhanced_csp --cov-report=xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

