name: Docker Publish

on:
  push:
    branches: ["main"]
    tags:
      - 'v1.*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: backend
            context: ./enhanced_csp/backend
            dockerfile: ./enhanced_csp/backend/Dockerfile
          - service: frontend
            context: ./enhanced_csp/frontend
            dockerfile: ./enhanced_csp/frontend/Dockerfile
          - service: exporters
            context: ./monitoring
            dockerfile: ./monitoring/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

